/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.surreal.samgen.modes.condition.node;

import org.surreal.samgen.modes.condition.analysis.*;

@SuppressWarnings("nls")
public final class AOpAtomic extends PAtomic
{
    private PLval _lval_;
    private POp _op_;
    private PRval _rval_;

    public AOpAtomic()
    {
        // Constructor
    }

    public AOpAtomic(
        @SuppressWarnings("hiding") PLval _lval_,
        @SuppressWarnings("hiding") POp _op_,
        @SuppressWarnings("hiding") PRval _rval_)
    {
        // Constructor
        setLval(_lval_);

        setOp(_op_);

        setRval(_rval_);

    }

    @Override
    public Object clone()
    {
        return new AOpAtomic(
            cloneNode(this._lval_),
            cloneNode(this._op_),
            cloneNode(this._rval_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpAtomic(this);
    }

    public PLval getLval()
    {
        return this._lval_;
    }

    public void setLval(PLval node)
    {
        if(this._lval_ != null)
        {
            this._lval_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lval_ = node;
    }

    public POp getOp()
    {
        return this._op_;
    }

    public void setOp(POp node)
    {
        if(this._op_ != null)
        {
            this._op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op_ = node;
    }

    public PRval getRval()
    {
        return this._rval_;
    }

    public void setRval(PRval node)
    {
        if(this._rval_ != null)
        {
            this._rval_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rval_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lval_)
            + toString(this._op_)
            + toString(this._rval_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lval_ == child)
        {
            this._lval_ = null;
            return;
        }

        if(this._op_ == child)
        {
            this._op_ = null;
            return;
        }

        if(this._rval_ == child)
        {
            this._rval_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lval_ == oldChild)
        {
            setLval((PLval) newChild);
            return;
        }

        if(this._op_ == oldChild)
        {
            setOp((POp) newChild);
            return;
        }

        if(this._rval_ == oldChild)
        {
            setRval((PRval) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
