/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.surreal.samgen.modes.condition.node;

import org.surreal.samgen.modes.condition.analysis.*;

@SuppressWarnings("nls")
public final class ASingletonAtomic extends PAtomic
{
    private PModename _modename_;

    public ASingletonAtomic()
    {
        // Constructor
    }

    public ASingletonAtomic(
        @SuppressWarnings("hiding") PModename _modename_)
    {
        // Constructor
        setModename(_modename_);

    }

    @Override
    public Object clone()
    {
        return new ASingletonAtomic(
            cloneNode(this._modename_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingletonAtomic(this);
    }

    public PModename getModename()
    {
        return this._modename_;
    }

    public void setModename(PModename node)
    {
        if(this._modename_ != null)
        {
            this._modename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modename_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._modename_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._modename_ == child)
        {
            this._modename_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._modename_ == oldChild)
        {
            setModename((PModename) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
